name: Make Dev Envfile

on:
  workflow_call:
    inputs:
      secrets:
        required: true
        type: map
      vars:
        required: true
        type: map

jobs:
  make-envfile:
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: dev
      - name: Make dev envfile
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envs: |
            DB_HOST=${{ inputs.secrets.DB_HOST }}
            DB_PORT=${{ inputs.vars.DB_PORT }}
            DB_USER=${{ inputs.vars.DB_USER }}
            DB_NAME=${{ inputs.vars.DB_NAME }}
            NODE_ENV=dev
            DB_DROP_SCHEMA=${{ inputs.secrets.DB_DROP_SCHEMA }}
            DB_PASSWORD=${{ inputs.vars.DB_PASSWORD }}
            AUTH_SECRET=${{ inputs.secrets.AUTH_SECRET }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
          directory: ./dev
