name: Make Dev Envfile

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  make-envfile:
    runs-on: [self-hosted, ${{ inputs.enviroment }}]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ inputs.enviroment }}
      - name: Make dev envfile
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_PORT: ${{ vars.DB_PORT }}
          envkey_DB_USER: ${{ vars.DB_USER }}
          envkey_DB_NAME: ${{ vars.DB_NAME }}
          envkey_NODE_ENV: dev
          envkey_DB_DROP_SCHEMA: ${{ secrets.DB_DROP_SCHEMA }}
          envkey_DB_PASSWORD: ${{vars.DB_PASSWORD}}
          envkey_AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
          directory: ./dev
