name: Create envfile

on:
  workflow_call:
    inputs:
      DEBUG:
        required: true
        type: boolean
      SOME_API_KEY:
        required: true
        type: string
      SECRET_KEY:
        required: true
        type: string
      SOME_ACTION_VARIABLE:
        required: true
        type: string
      SOME_OTHER_VARIABLE:
        required: false
        type: string
        default: "foobar"
      DIRECTORY:
        required: true
        type: string
      FILE_NAME:
        required: true
        type: string

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
            envkey_DB_HOST: ${{ vars.PROD_DB_HOST }}
            envkey_DB_PORT: ${{ vars.PROD_DB_PORT }}
            envkey_DB_USER: ${{ vars.PROD_DB_USER }}
            envkey_DB_NAME: ${{ vars.PROD_DB_NAME }}
            envkey_NODE_ENV: prod
            envkey_DB_DROP_SCHEMA: 0
            envkey_JWT_EXPIRES_IN: ${{ vars.PROD_JWT_EXPIRES_IN }}
            envkey_SECRET_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
            envkey_SECRET_JWT_SECRET: ${{ secrets.PROD_JWT_SECRET }}
            file_name: prod.env
            fail_on_empty: false
            sort_keys: false
