name: Dev deploy

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, dev]
    defaults:
      run: 
        working-directory: ./dev/

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: dev
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: './dev/package-lock.json'
    - run: npm ci
    - name: Log Environment Variables
      run: env
    - name: Docker Compose up
      run: docker compose up -d
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ vars.DB_PORT }}
        DB_USER: ${{ vars.DB_USER }}
        DB_PASSWORD: ${{ vars.DB_PASSWORD }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_DROP_SCHEMA: ${{ secrets.DB_DROP_SCHEMA }}
        AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

    - run: npm run build --if-present
    - name: Restart PM2
      run: pm2 restart ./dist/src/main.js --update-env
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ vars.DB_PORT }}
        DB_USER: ${{ vars.DB_USER }}
        DB_PASSWORD: ${{ vars.DB_PASSWORD }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_DROP_SCHEMA: ${{ secrets.DB_DROP_SCHEMA }}
        AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
