name: Dev deploy

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, dev]
    environment: dev
    defaults:
      run: 
        working-directory: ./dev/


    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: dev
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: './dev/package-lock.json'
      
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('dev/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
  
    - run: npm ci
    
    - name: Call Make dev envfile
      uses: ./.github/reuse/create-env/
      with:
        environment: dev
  
    - name: Docker Compose up
      run: docker compose up -d
    
    - run: npm run build --if-present
    - name: Restart PM2
      run: pm2 restart ./dist/main.js --update-env
